name: Extraer HLS Links

on:
  schedule:
    - cron: "0 * * * *"  # Cada hora
  workflow_dispatch:      # Permite ejecución manual

jobs:
  extract-hls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          pip install playwright
          playwright install --with-deps chromium

      - name: Ejecutar script
        run: |
          echo "[INFO] Ejecutando extract_hls_multi.py"
          python3 extract_hls_multi.py

      - name: Subir cambios al repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update HLS links" || echo "No hay cambios"
          git push
