name: YouTube HLS Finder

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # Cada hora

jobs:
  scrape-hls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Restaurar storage_state.json desde Secret
        run: |
          echo "${{ secrets.YT_STORAGE_STATE }}" | base64 --decode > storage_state.json
          echo "[INFO] storage_state.json restaurado"

      - name: Ejecutar script
        run: |
          python youtube_hls_finder.py scrape urls.txt -o streams.m3u

      - name: Commit & Push streams.m3u
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add streams.m3u
          git commit -m "Actualización automática de playlist" || echo "Sin cambios"
          git push